# Generated by Django 3.2.3 on 2021-07-31 16:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YelpBusinessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 7, 31, 22, 48, 40, 646360))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=7)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField()),
                ('reviewer', models.TextField()),
                ('reviewer_address', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 7, 31, 22, 48, 40, 646360))),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.yelpbusinessitem')),
            ],
        ),
    ]
