# Generated by Django 3.2.3 on 2021-09-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210920_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpbusinessitem',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='yelpbusinessitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
